#Name of the GitHub Action
name: Deploy Logic APp

#Set the action on which the workflow will trigger

on:
 push:
   branches:
     - master

env:
  ENV_RESOURCEGROUP: az-logicapp-githubactions-demo-rg
  ENV_RESOURCEGROUPLOCATION: australiaeast

jobs:
  validate-and-deploy:
   runs-on: ubuntu-latest
   steps:
    
    #Checkout the repository
    - name: Checout Repository
    - run: actions/checkout@master

    # Create the resource group

    - name: Create Resource Group
    - run: az group create -n ${{ENV_RESOURCEGROUP}} -l ENV_RESOURCEGROUPLOCATION
    - uses: azure/login@v1
      with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
    
    # Log Out From Azure 

    - name: Logout
    - run: az logout
