#Name of the GitHub Action
name: Deploy Logic App

#Set the action on which the workflow will trigger
on:
 push:
   branches:
     - master

env:
  ENV_RESOURCEGROUP: az-logicapp-githubactions-demo-rg
  ENV_RESOURCEGROUPLOCATION: australiaeast

jobs:
  validate-and-deploy:
   runs-on: ubuntu-latest
   steps:

    #Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@master

    #Use the azure provided action to log on to azure using service pricipal
    - name: Login to Azure
      uses: azure/login@v1
      with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
    
    # Create the resource group
    - name: Create Resource Group
      run: az group create -n ${{env.ENV_RESOURCEGROUP}} -l ${{env.ENV_RESOURCEGROUPLOCATION}}
      
    # Log Out From Azure 
    - name: Logout
      run: az logout
